### ISSUE TITLE
Data dropdowns only open on every second click in chrome

### ISSUE THREAD

**Issue by schaubli** [reymond-group/faerun#3]
When the database dropdown is clicked, it closes right after opening again. This happens every second time and only appears to be a problem in Chrome (I tested Safari and Firefox as well). 
Here is a gif of the dropdown closing right after opened every second time.

![faerun_dropdown_bug](https://user-images.githubusercontent.com/18361732/60419836-86ed6900-9be6-11e9-9bd4-21794f6f3cc8.gif)

@daenuprobst do you have and idea what's causing this?

**Comment by schaubli** [comment]
Okay, I solved this by using a compiled version of the materialize framework from their GitHub in the master branch (they haven't yet released a version that fixes this bug): https://github.com/Dogfalo/materialize/commit/e3eb698a07fec1d3111c1786bf502f0225bdfbda

It seems to be solved by this pull request which also contains instructions on how to compile it: https://github.com/Dogfalo/materialize/pull/6339
Initially addressed by this issue: https://github.com/Dogfalo/materialize/issues/6336

The materialize version that faerun uses should be updated, once materialize publishes a new release version with this fix.

**Comment by daenuprobst** [comment]
Thanks for the info @Schaubli, if been accessing it using Firefox. If they don't release a fix relatively soon, I will include a fallback to the default drop down in chrome.

**Comment by daenuprobst** [comment]
Fixed by https://github.com/reymond-group/faerun/commit/cdd49e37c88a17950ec42e1d992541e89aa8f33e
